[template]
ignore = ["LICENSE", "README.md", ".jj"]

[placeholders]
features = { prompt = "Which bevy features would you like?", choices = [
  "2D",
  "3D",
  "None",
  "Default"
] }
web = { prompt = "Would you like to export your game to the web?", type = "bool", default = true }
justfile = { prompt = "Would you like a justfile?", type = "bool", default = true }

[conditional.'justfile'.placeholders]
itch = { prompt = "Would you like to publish to itch.io?", type = "bool", default = false }

[conditional.'itch'.placeholders]
itch-page = { prompt = "What's your itch.io page? (user/game)" }

[conditional.'features == "2D"'.placeholders]
nearest_filter = { prompt = "Would you like to use the 'nearest' filter? (for pixel art)", type = "bool", default = false }
